server:
    port: 8081

spring: 
    datasource:
        url: jdbc:mysql://userdatabase.c6alrefsv5hc.us-west-1.rds.amazonaws.com:3306/awsuserdb
        username: admin
        password: root1234
    
    jpa:
        hibernate:
          ddl-auto: update     
        
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect