server:
  port: 8082

spring:
    datasource:
        #url: jdbc:mysql://localhost:3306/inventory
        #username: root
        #password: root
        url: jdbc:mysql://userdatabase.c6alrefsv5hc.us-west-1.rds.amazonaws.com:3306/awsinventory
        username: admin
        password: root1234
    
    jpa:
        hibernate:
          ddl-auto: update     
        
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
   # hostname: http://localhost:8761
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

  client:
    service-url:
      #defultZone: http://localhost:8761/eureka 
       defaultZone: http://SpringDiscoveryServer-env.5iczumju8b.us-west-1.elasticbeanstalk.com/eureka
